services:
  - type: web
    name: bigdata-backend
    env: go

    build:
      version: 1.25.3          # ðŸ”¥ THIS IS REQUIRED
      buildCommand: "go build -o app ./cmd/server"

    startCommand: "./app"

    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: CLICKHOUSE_URL
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
